### ISSUE TITLE
DeltaDTM scripts

### ISSUE THREAD

**Issue by ravisukhadiya** [evetion/DeltaDTM.jl#1]
Hi,
I am beginner to julia language and also new to the Lidar datasets as well. Sorry, my question might be silly. 
I have downloaded the datasets and saved Lidar data in .parquet format. My question is that do I have to store all .parquet data of each Lidar dataset in .gpkg? Another question is do I have to store data in the given structure of the folder as given in script as below:

 tile = joinpath(folder, "copernicus/copernicus2", tilename)
        otile = joinpath(folder, "copernicus/copernicus_orig/elevation", tilename)
        etile = joinpath(folder, "copernicus/copernicus_orig/error", tilename)
        mtile = joinpath(folder, "copernicus/copernicus_orig/masks", tilename)
        mtiles = joinpath(folder, "copernicus/copernicus_orig/masks", tilefilename)
        ctile = joinpath(folder, "esa-worldcover-2021/copernicus2", tilename)
        icefn = joinpath(folder, "bias3/$(tilef)/bias.txt")
        gedifn = joinpath(folder, "biasg2/$(tilef)/bias.txt")

**Comment by evetion** [comment]
Hi @ravisukhadiya, happy to take questions here. Getting this to work without experience with both the data and Julia might be hard, especially as I haven't yet found time to improve the accessibility of the code base. You did find the relevant [lines](https://github.com/evetion/DeltaDTM.jl/blob/main/scripts/dtm_call.jl#L40C47-L48C62) though, let me explain them here.

```julia
# A CopernicusDEM elevation tile with all water values masked
tile = joinpath(folder, "copernicus/copernicus2", tilename)
# An original CopernicusDEM tile
otile = joinpath(folder, "copernicus/copernicus_orig/elevation", tilename)
# An original CopernicusDEM error tile
etile = joinpath(folder, "copernicus/copernicus_orig/error", tilename)
# An original CopernicusDEM mask tile
mtile = joinpath(folder, "copernicus/copernicus_orig/masks", tilename)
# A duplicate of the above, will be removed in the future
mtiles = joinpath(folder, "copernicus/copernicus_orig/masks", tilefilename)

# A ESA WorldCover tile, warped to the same size/extents as the CopernicusDEM tiles above
ctile = joinpath(folder, "esa-worldcover-2021/copernicus2", tilename)

# The naming is bad, but this is a txt file of a list of .pq files containing ICESat-2 points
icefn = joinpath(folder, "bias3/$(tilef)/bias.txt")
# The naming is bad, but this is a txt file of a list of .pq files containing GEDI points
gedifn = joinpath(folder, "biasg2/$(tilef)/bias.txt")

```

Note that all tiff files need to have the same size/extent. For DeltaDTM I've preprocessed CopernicusDEM to COG and cutoff one row/column so the tiles are 3600x3600, like done for https://copernicus-dem-30m.s3.amazonaws.com/readme.html. I've used gdalwarp to warp the ESA WorldCover dataset to the same tiles (and filenames, with only the folder distinguishing the dataset).

With regards to ICESat-2 and GEDI data, I've used my package https://github.com/evetion/SpaceLiDAR.jl to download and process the satellite lidar data. Specifically, I've tiled each individual granule to 1x1 degree (like all tiff files) parquet files, and for each tile I've saved all those intersecting granules to a .txt file.

Doing the above globally takes a *lot* of preprocessing and time, so I would advise starting with a single tile first. For scaling globally I replaced single tiff files with a .vrt file of that tiff file and all its neighbours (so 3x3 degree tiles really when all tiles are there) to prevent edge artefacts.

Furthermore, I aim to significantly improve the accessibility of the package in the coming months, including a test (notebook?) with some test data so you can fully reproduce the workflow.

**Comment by ravisukhadiya** [comment]
Hi Maarten,
Thank you so much for a detailed clarification. It's really useful. 
It's true that it will take a long to process globally. Anyway, I am working on a single tile as a pilot run.
Looking forward to see an update on the code.
Thanks!
